### ISSUE TITLE
images in overview have no alt-attributes

### ISSUE THREAD

**Issue by frase-git** [cmb69/foldergallery_xh#46]
Die Bilder in der Galerieübersicht haben ein `title`- aber kein `alt`-Attribut.
Der Link hat ebenfalls ein `title`-Attribut.
Das ergibt einen "Tooltipp" bei hover = für mich unerwünscht, zumal hier die Bildbeschreibung genutzt wird.
Ich denke beide `title`s könnten weg und nur das `alt` sollte zu den Bildern.

**Comment by cmb69** [comment]
See https://cmsimpleforum.com/viewtopic.php?f=16&t=12648&p=66350#p66350.

**Comment by frase-git** [comment]
Lighthouse unter Chrome, stuft die Seiten unter „Barrierefreiheit“ und „SEO“ aufgrund der fehlenden Alt-Attribute stark herab.

**Comment by cmb69** [comment]
> Lighthouse unter Chrome, stuft die Seiten unter „Barrierefreiheit“ und „SEO“ aufgrund der fehlenden Alt-Attribute stark herab.

Ja, und vermutlich ist für das Tool alles okay, wenn man `alt="some description"` angibt. Klar, ich kann einfach den selben Text wie für den `title` nehmen (wenn das überhaupt geht; kann sein, dass Photoswipe das von selbst macht), aber vermutlich ist das in der Praxis auch nicht wirklich sinnvoll. Ein vernünftiger `alt` Text für ein Bild namens stork.jpeg könnte z.B. sein: "A stork standing in its nest at the top of a yellow stone building with the edge of red roof tiles showing, against a very clear blue sky." Aber wo soll diese Info bei Foldergallery her kommen?

Aber gut, ich schau mir das mal näher an.

**Comment by frase-git** [comment]
> Aber wo soll diese Info bei Foldergallery her kommen?

Wir können nicht zaubern, das ist klar.
Wenn man davon ausgeht, dass der Bild-Titel einigermaßen vernünftig gewählt wurde, dann ist ein Alt-Tag mit gleichem Inhalt immer noch besser, als gar keiner.

Warum welches Tool was und wie beurteilt, sollte uns eigentlich egal sein :(
Wenn wir aber eine Herabstufung vermeiden können, dann sollten wir das tun.

**Comment by cmb69** [comment]
Ich hab's mir gerade genauer angeschaut, und mich gewundert warum da kein `title` ist; das hatte ich als #24 bereits behoben. Im Wesentlichen wird nun statt dem `title` eine `<figcaption>` erzeugt. Vielleicht genügt das schon? Ansonsten kannst du die `alt` Attribute in  views/gallery.php auch testweise ergänzen (`alt="<?=$child->caption?>"`).

**Comment by frase-git** [comment]
`<figcaption>` ist gut, das Alt-Attribut wird trotzdem angemeckert (Barriere 80%).

`alt="<?=$child->caption?>` bringt schlagartig „Barrierefreiheit = 100%" und "SEO“ macht auch einen gewaltigen Sprung nach oben.
Das sollte die wirklich **schnelle** und **simple** Lösung des Problems sein.
Danke!

**Comment by cmb69** [comment]
Okay, dann machen wir das halt so. :)

**Comment by frase-git** [comment]
You are the best! It really helped.
