### ISSUE TITLE
Make foldergallery fit for php 8.x

### ISSUE THREAD

**Issue by frase-git** [cmb69/foldergallery_xh#50]
Version: **1.0beta1**

I hope it's not another duplicate entry.
;-)
Under PHP 8.1 the debug mode reports:

> DEPRECATED: Return type of Pfw\View\ArrayViewValue::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\pfw\classes\View\ArrayViewValue.php:31
> DEPRECATED: Return type of Pfw\View\ArrayViewValue::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\pfw\classes\View\ArrayViewValue.php:47
> DEPRECATED: Return type of Pfw\View\ArrayViewValue::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\pfw\classes\View\ArrayViewValue.php:39
> DEPRECATED: Return type of Pfw\View\ArrayViewValue::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\pfw\classes\View\ArrayViewValue.php:63
> DEPRECATED: Return type of Pfw\View\ArrayViewValue::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\pfw\classes\View\ArrayViewValue.php:55

**Comment by cmb69** [comment]
Yeah, that's actually a Pfw_XH isses (and already filed as https://github.com/cmb69/pfw_xh/issues/34). Anyhow, doesn't matter since the Pfw_XH dependency has been removed (ad915f62ce3e4659fa8bd733cbb03f23e6b9d356).
