### ISSUE TITLE
Generate thumbnails on the fly

### ISSUE THREAD

**Issue by cmb69** [cmb69/foldergallery_xh#52]
A couple of issues regarding the thumbnail cache have already been filed (#40, #44, #47), and there are more (e.g. no cache eviction is implemented; the implementation is somewhat ugly), and after all, the caching may have been a premature optimization.

Thus, I'm going to drop the caching altogether. It could still be brought back, if there is a *real* need to cache the thumbnails server-side.

**Comment by frase-git** [comment]
> Thus, I'm going to drop the caching altogether. It could still be brought back, if there is a real need to cache the thumbnails server-side.

Comprehension question:
Does this mean that there will be no more thumbnails at all?
Will the original images always be loaded in full size in the gallery overview from now on?
I hope very much that I am wrong there.
